# Generated by Django 4.1.3 on 2022-12-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FreeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='000', max_length=4)),
                ('space', models.SmallIntegerField(default=1)),
                ('is_hotwater', models.SmallIntegerField(default=0)),
                ('is_computer', models.SmallIntegerField(default=0)),
                ('is_used', models.SmallIntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.floor')),
            ],
        ),
    ]
